// Registry of approved AI designs. Generated by scripts/design.mjs; each
// entry is a design that compiled clean and passed the independent review.
import type { ApprovedDesign } from "./types.ts";

export const APPROVED_DESIGNS: ApprovedDesign[] = [];
