// Persist an approved design so the app, manuals and validator pick it up:
// src/designs/<id>.ts (spec + review record), the registry index, and the
// approved render under public/designs/ for the gallery.

import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function saveApproved(root, result, { model, effort, runId }) {
  const designs = join(root, "src/designs");
  let id = result.spec.id;
  // never overwrite an approved design: number a new one
  for (let n = 2; existsSync(join(designs, `${id}.ts`)); n++) id = `${result.spec.id}-${n}`;
  const spec = { ...result.spec, id };
  let image;
  if (result.png && existsSync(result.png)) {
    mkdirSync(join(root, "public/designs"), { recursive: true });
    copyFileSync(result.png, join(root, "public/designs", `${id}.png`));
    image = `/designs/${id}.png`;
  }
  const record = {
    spec,
    subject: result.subject,
    model,
    effort,
    approvedAt: new Date().toISOString(),
    runId,
    costUsd: result.cost.usd,
    image,
    notes: result.notes ?? "",
    review: {
      guess: result.review.guess,
      quality: result.review.quality,
      fidelity: result.review.fidelity,
      recognisable: result.review.recognisable,
      verdict: result.review.verdict,
      strengths: result.review.strengths ?? [],
      issues: result.review.issues ?? [],
    },
  };
  writeFileSync(join(designs, `${id}.ts`),
    `// Approved AI design, written by scripts/design.mjs. Edit the spec and\n// re-run the checks rather than editing placements; they are compiled.\nimport type { ApprovedDesign } from "./types.ts";\n\nconst design: ApprovedDesign = ${JSON.stringify(record, null, 2)};\n\nexport default design;\n`);
  writeIndex(root);
  return id;
}

export function writeIndex(root) {
  const designs = join(root, "src/designs");
  const files = readdirSync(designs).filter((f) => f.endsWith(".ts") && !["index.ts", "types.ts"].includes(f)).sort();
  const names = files.map((f, i) => [`d${i}`, f]);
  writeFileSync(join(designs, "index.ts"),
    `// Registry of approved AI designs. Generated by scripts/design.mjs; each\n// entry is a design that compiled clean and passed the independent review.\nimport type { ApprovedDesign } from "./types.ts";\n${names.map(([v, f]) => `import ${v} from "./${f}";`).join("\n")}\n\nexport const APPROVED_DESIGNS: ApprovedDesign[] = [${names.map(([v]) => v).join(", ")}];\n`);
}
